### PR TITLE
tools: add WPT updater for specific subsystems

### PR DESCRIPTION
**Pull request by mertcanaltin**
https://github.com/nodejs/node/pull/54460 I'll test here

### CODE REVIEW

**Comment by mertcanaltin** [comment]
Do we need to merge it? @panva

**Comment by panva** [comment]
You can force push your changes to main here and run workflow_dispatch then, just make sure to force push main to what main is in nodejs/node after you're done testing.

**Comment by mertcanaltin** [comment]
> You can force push your changes to main here and run workflow_dispatch then, just make sure to force push main to what main is in nodejs/node after you're done testing.

I understand, thank you very much for teaching me this.

**Comment by mertcanaltin** [comment]
I tried to forcibly push it to the master but it gave me a permission error because I didn't have permission :(

**Comment by panva** [comment]
> I tried to forcibly push it to the master but it gave me a permission error because I didn't have permission :(

Sorry, must be that you're part of the Triagers team.

**Comment by mertcanaltin** [comment]
> > I tried to forcibly push it to the master but it gave me a permission error because I didn't have permission :(
> 
> Sorry, must be that you're part of the Triagers team.

I'm actually on the triage team.

**Comment by panva** [comment]
> > > I tried to forcibly push it to the master but it gave me a permission error because I didn't have permission :(
> > 
> > 
> > Sorry, must be that you're part of the Triagers team.
> 
> I'm actually on the triage team.

Exactly. A collaborator could push here.

**Comment by mertcanaltin** [comment]
hmm I understand, I hope I can be soon ❤️  😄

**Comment by mertcanaltin** [comment]
@aduh95 Hello, I wonder if you could push this when you're free.

**Comment by mertcanaltin** [comment]
I am closing it as it is no longer needed, thanks everyone

**Pull request closed without merging**
