### PR TITLE
doc: update README to test PR squashing

### PR DESCRIPTION
**Pull request by aduh95-test-account**
This is a test.

### CODE REVIEW

**Review by aduh95 — APPROVED** [review]

**Comment by aduh95** [comment]
@targos can you approve this PR so it can be fast-tracked please?

**Review by targos — APPROVED** [review]

**Comment by targos** [comment]
>    ✖  GitHub CI is still running

Maybe we should try to contact GitHub's support about this. It happens sometimes that the API reports pending checks that don't seem to exist.

**Comment by aduh95** [comment]
> > ✖  GitHub CI is still running
> 
> Maybe we should try to contact GitHub's support about this. It happens sometimes that the API reports pending checks that don't seem to exist.

Maybe we could also update ncu to ignore those ghost checks. Here's the result of `gh api graphql -F prid=40 -F owner=nodejs -F repo=node-auto-test -f query="$(cat …/node-core-utils/lib/queries/PRCommits.gql)"`:

```json
{
  "data": {
    "repository": {
      "pullRequest": {
        "commits": {
          "nodes": [
            {
              "commit": {
                "checkSuites": {
                  "nodes": [
                    {
                      "url": "https://github.com/nodejs/node-auto-test/commit/f5b0a228f2265278d1a79bfe4c2affda1d6c2506/checks?check_suite_id=4212366327",
                      "conclusion": null,
                      "status": "QUEUED"
                    },
                    {
                      "url": "https://github.com/nodejs/node-auto-test/commit/f5b0a228f2265278d1a79bfe4c2affda1d6c2506/checks?check_suite_id=4212368587",
                      "conclusion": "SUCCESS",
                      "status": "COMPLETED"
                    }
                  ]
                },
                "status": null
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by targos** [comment]
How do we know it's a ghost check?

**Comment by aduh95** [comment]
> How do we know it's a ghost check?

Not sure, but if the `conclusion` is `null` that seems like a good reason:

> The final conclusion of the check. Can be one of action_required, cancelled, failure, neutral, success, skipped, stale, or timed_out.

Also, we could see if there is another check with the same `id` that has completed for the same commit.

**Comment by targos** [comment]
> Not sure, but if the conclusion is null that seems like a good reason

I think it's `null` because the check is still `QUEUED`, which is probably also the case for legit checks (like macOS runs that are waiting for a runner in the pool).

**Comment by targos** [comment]
I created a support ticket.

**Comment by aduh95** [comment]
I tried disabling the remaining check and there's still a ghost check:

```json
{
  "commit": {
    "checkSuites": {
      "nodes": [
        {
          "id": "CS_kwDOBnE3X877F1R5",
          "url": "https://github.com/nodejs/node-auto-test/commit/ac4732311b17df7e1e751e6bb498c6f9611eace0/checks?check_suite_id=4212610169",
          "conclusion": null,
          "status": "QUEUED",
          "resourcePath": "/nodejs/node-auto-test/commit/ac4732311b17df7e1e751e6bb498c6f9611eace0/checks?check_suite_id=4212610169",
          "workflowRun": null
        }
      ]
    },
    "status": null
  }
}
```

**Comment by aduh95** [comment]
Digging a bit more into this, it looks like this is related to Dependabot (which is disabled in this repo):

<details>

From this `…/node-core-utils/lib/queries/PRCommits.gql` file:

```gql
query Commits($prid: Int!, $owner: String!, $repo: String!, $after: String) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $prid) {
      commits(last: 100, after: $after) {
        nodes {
          commit {
            checkSuites(first: 10) {
              nodes {
                id,
                databaseId,
                url,
                conclusion,
                status,
                resourcePath,
                createdAt,
                creator {
                  login
                },
                workflowRun {
                  resourcePath,
                  runNumber,
                  url,
                  workflow {
                    name
                  }
                }
              }
            }
            status {
              state
            }
          }
        }
      }
    }
  }
}
```

```sh
gh api graphql -F prid=40 -F owner=nodejs -F repo=node-auto-test -f query="$(cat …/node-core-utils/lib/queries/PRCommits.gql)"
```

```json
{
  "commit": {
    "checkSuites": {
      "nodes": [
        {
          "id": "CS_kwDOBnE3X877GAW-",
          "databaseId": 4212655550,
          "url": "https://github.com/nodejs/node-auto-test/commit/9aa5d82c4aaaba774336855f0e9c111d4878867e/checks?check_suite_id=4212655550",
          "conclusion": null,
          "status": "QUEUED",
          "resourcePath": "/nodejs/node-auto-test/commit/9aa5d82c4aaaba774336855f0e9c111d4878867e/checks?check_suite_id=4212655550",
          "createdAt": "2021-10-31T11:30:20Z",
          "creator": {
            "login": "aduh95"
          },
          "workflowRun": null
        }
      ]
    }
  }
}
```

```sh
gh api repos/nodejs/node-auto-test/check-suites/4212655550
```

```json
{
  "id": 4212655550,
  "node_id": "CS_kwDOBnE3X877GAW-",
  "head_branch": "test-pr-squashing",
  "head_sha": "9aa5d82c4aaaba774336855f0e9c111d4878867e",
  "status": "queued",
  "conclusion": null,
  "url": "https://api.github.com/repos/nodejs/node-auto-test/check-suites/4212655550",
  "before": "ac4732311b17df7e1e751e6bb498c6f9611eace0",
  "after": "9aa5d82c4aaaba774336855f0e9c111d4878867e",
  "pull_requests": [
    {
      "url": "https://api.github.com/repos/nodejs/node-auto-test/pulls/40",
      "id": 769894623,
      "number": 40,
      "head": {
        "ref": "test-pr-squashing",
        "sha": "9aa5d82c4aaaba774336855f0e9c111d4878867e",
        "repo": {
          "id": 108083039,
          "url": "https://api.github.com/repos/nodejs/node-auto-test",
          "name": "node-auto-test"
        }
      },
      "base": {
        "ref": "main",
        "sha": "dd66ba5fd90aa96dab3d02edede4886d475d44ff",
        "repo": {
          "id": 108083039,
          "url": "https://api.github.com/repos/nodejs/node-auto-test",
          "name": "node-auto-test"
        }
      }
    }
  ],
  "app": {
    "id": 29110,
    "slug": "dependabot",
    "node_id": "MDM6QXBwMjkxMTA=",
    "owner": {
      "login": "github",
      "id": 9919,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github",
      "html_url": "https://github.com/github",
      "followers_url": "https://api.github.com/users/github/followers",
      "following_url": "https://api.github.com/users/github/following{/other_user}",
      "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github/subscriptions",
      "organizations_url": "https://api.github.com/users/github/orgs",
      "repos_url": "https://api.github.com/users/github/repos",
      "events_url": "https://api.github.com/users/github/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "name": "Dependabot",
    "description": "",
    "external_url": "https://dependabot-api.githubapp.com",
    "html_url": "https://github.com/apps/dependabot",
    "created_at": "2019-04-16T22:34:25Z",
    "updated_at": "2019-07-01T21:20:42Z",
    "permissions": {
      "checks": "write",
      "contents": "write",
      "issues": "write",
      "members": "read",
      "metadata": "read",
      "pull_requests": "write",
      "statuses": "read",
      "workflows": "write"
    },
    "events": [
      "check_suite",
      "issues",
      "issue_comment",
      "label",
      "pull_request",
      "pull_request_review",
      "pull_request_review_comment",
      "repository"
    ]
  },
  "created_at": "2021-10-31T11:30:20Z",
  "updated_at": "2021-10-31T11:30:20Z",
  "latest_check_runs_count": 0,
  "check_runs_url": "https://api.github.com/repos/nodejs/node-auto-test/check-suites/4212655550/check-runs",
  "head_commit": {
    "id": "9aa5d82c4aaaba774336855f0e9c111d4878867e",
    "tree_id": "d2001aa655259adb543683d0130bea48616d166f",
    "message": "fixup! doc: update README to test PR squashing",
    "timestamp": "2021-10-31T11:30:12Z",
    "author": {
      "name": "Antoine du Hamel",
      "email": "duhamelantoine1995@gmail.com"
    },
    "committer": {
      "name": "Antoine du Hamel",
      "email": "duhamelantoine1995@gmail.com"
    }
  },
  "repository": {
    "id": 108083039,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMDgwODMwMzk=",
    "name": "node-auto-test",
    "full_name": "nodejs/node-auto-test",
    "private": false,
    "owner": {
      "login": "nodejs",
      "id": 9950313,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9950313?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nodejs",
      "html_url": "https://github.com/nodejs",
      "followers_url": "https://api.github.com/users/nodejs/followers",
      "following_url": "https://api.github.com/users/nodejs/following{/other_user}",
      "gists_url": "https://api.github.com/users/nodejs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nodejs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nodejs/subscriptions",
      "organizations_url": "https://api.github.com/users/nodejs/orgs",
      "repos_url": "https://api.github.com/users/nodejs/repos",
      "events_url": "https://api.github.com/users/nodejs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nodejs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/nodejs/node-auto-test",
    "description": "Node.js clone for testing automation tools",
    "fork": false,
    "url": "https://api.github.com/repos/nodejs/node-auto-test",
    "forks_url": "https://api.github.com/repos/nodejs/node-auto-test/forks",
    "keys_url": "https://api.github.com/repos/nodejs/node-auto-test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/nodejs/node-auto-test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/nodejs/node-auto-test/teams",
    "hooks_url": "https://api.github.com/repos/nodejs/node-auto-test/hooks",
    "issue_events_url": "https://api.github.com/repos/nodejs/node-auto-test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/nodejs/node-auto-test/events",
    "assignees_url": "https://api.github.com/repos/nodejs/node-auto-test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/nodejs/node-auto-test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/nodejs/node-auto-test/tags",
    "blobs_url": "https://api.github.com/repos/nodejs/node-auto-test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/nodejs/node-auto-test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/nodejs/node-auto-test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/nodejs/node-auto-test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/nodejs/node-auto-test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/nodejs/node-auto-test/languages",
    "stargazers_url": "https://api.github.com/repos/nodejs/node-auto-test/stargazers",
    "contributors_url": "https://api.github.com/repos/nodejs/node-auto-test/contributors",
    "subscribers_url": "https://api.github.com/repos/nodejs/node-auto-test/subscribers",
    "subscription_url": "https://api.github.com/repos/nodejs/node-auto-test/subscription",
    "commits_url": "https://api.github.com/repos/nodejs/node-auto-test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/nodejs/node-auto-test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/nodejs/node-auto-test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/nodejs/node-auto-test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/nodejs/node-auto-test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/nodejs/node-auto-test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/nodejs/node-auto-test/merges",
    "archive_url": "https://api.github.com/repos/nodejs/node-auto-test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/nodejs/node-auto-test/downloads",
    "issues_url": "https://api.github.com/repos/nodejs/node-auto-test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/nodejs/node-auto-test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/nodejs/node-auto-test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/nodejs/node-auto-test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/nodejs/node-auto-test/labels{/name}",
    "releases_url": "https://api.github.com/repos/nodejs/node-auto-test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/nodejs/node-auto-test/deployments"
  }
}
```
</details>

I'll try to re-enable it to see if that updates the status.

**Comment by targos** [comment]
Maybe let's keep this PR open (so GitHub support can analyze it) and open a new one to test the commit queue?

**Comment by aduh95** [comment]
Just tried on #41, there's still a ghost PR check :/ Not sure what can be done in the mean time...

```json
{
  "commit": {
    "checkSuites": {
      "nodes": [
        {
          "id": "CS_kwDOBnE3X877IFeF",
          "databaseId": 4213200773,
          "url": "https://github.com/nodejs/node-auto-test/commit/3d871f0a8c57f45575d700fcf731e1a3163e73f8/checks?check_suite_id=4213200773",
          "conclusion": null,
          "status": "QUEUED",
          "resourcePath": "/nodejs/node-auto-test/commit/3d871f0a8c57f45575d700fcf731e1a3163e73f8/checks?check_suite_id=4213200773",
          "createdAt": "2021-10-31T14:04:31Z",
          "creator": {
            "login": "aduh95"
          },
          "workflowRun": null
        }
      ]
    },
    "status": null
  }
}

```

**Comment by aduh95-test-account** [comment]
> > Not sure, but if the conclusion is null that seems like a good reason
> 
> I think it's `null` because the check is still `QUEUED`, which is probably also the case for legit checks (like macOS runs that are waiting for a runner in the pool).

I've just checked this, it looks like `workflowRun` being `null` is a good hint that the reported check suite is not genuine:

```json
{
  "commit": {
    "checkSuites": {
      "nodes": [
        {
          "id": "CS_kwDOBnE3X8793Hnf",
          "databaseId": 4259084767,
          "url": "https://github.com/nodejs/node-auto-test/commit/fdd090771820b996b2f987562cc669088e30a676/checks?check_suite_id=4259084767",
          "conclusion": null,
          "status": "QUEUED",
          "resourcePath": "/nodejs/node-auto-test/commit/fdd090771820b996b2f987562cc669088e30a676/checks?check_suite_id=4259084767",
          "createdAt": "2021-11-04T17:36:13Z",
          "creator": {
            "login": "aduh95-test-account"
          },
          "workflowRun": {
            "resourcePath": "/nodejs/node-auto-test/actions/runs/1422486714",
            "runNumber": 53,
            "url": "https://github.com/nodejs/node-auto-test/actions/runs/1422486714",
            "workflow": {
              "name": "Commit messages adheres to guidelines at https://goo.gl/p2fr5Q"
            }
          }
        }
      ]
    },
    "status": null
  }
}
```

**Pull request closed without merging**
